/*
  # Appointments Table

  1. New Tables
    - `appointments` - Client appointments with booking details and status tracking
    
  2. Security
    - Enable RLS with public insert access and admin read/update/delete access
    - Prevent double bookings with unique constraint
*/

CREATE TABLE IF NOT EXISTS appointments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id uuid NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
  client_name text NOT NULL,
  client_email text NOT NULL,
  client_phone text NOT NULL,
  appointment_date date NOT NULL,
  appointment_time time NOT NULL,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(appointment_date, appointment_time)
);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Appointments readable by admin only" ON appointments;

CREATE POLICY "Appointments readable by admin only"
  ON appointments FOR SELECT
  TO authenticated
  USING (auth.jwt() ->> 'email' IN (SELECT email FROM admin_users));

DROP POLICY IF EXISTS "Appointments can be inserted by anyone" ON appointments;

CREATE POLICY "Appointments can be inserted by anyone"
  ON appointments FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Appointments can be updated by admin" ON appointments;

CREATE POLICY "Appointments can be updated by admin"
  ON appointments FOR UPDATE
  TO authenticated
  USING (auth.jwt() ->> 'email' IN (SELECT email FROM admin_users))
  WITH CHECK (auth.jwt() ->> 'email' IN (SELECT email FROM admin_users));

DROP POLICY IF EXISTS "Appointments can be deleted by admin" ON appointments;

CREATE POLICY "Appointments can be deleted by admin"
  ON appointments FOR DELETE
  TO authenticated
  USING (auth.jwt() ->> 'email' IN (SELECT email FROM admin_users));

CREATE INDEX IF NOT EXISTS idx_appointments_date ON appointments(appointment_date);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments(status);
CREATE INDEX IF NOT EXISTS idx_appointments_service_id ON appointments(service_id);
CREATE INDEX IF NOT EXISTS idx_appointments_date_time ON appointments(appointment_date, appointment_time);
