/*
  # Convert appointments ID to integer and expose ID generator

  1. Convert `appointments.id` from uuid to integer identity (for existing projects).
  2. Preserve old uuid IDs in `legacy_uuid_id` only as historical reference.
  3. Create RPC function `next_appointment_id()` so public booking can reserve a numeric ID
     without requiring SELECT permissions on appointments.
*/

DO $$
DECLARE
  current_udt_name text;
BEGIN
  SELECT c.udt_name
  INTO current_udt_name
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
    AND c.table_name = 'appointments'
    AND c.column_name = 'id';

  IF current_udt_name = 'uuid' THEN
    ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS appointments_pkey;
    ALTER TABLE public.appointments RENAME COLUMN id TO legacy_uuid_id;
    ALTER TABLE public.appointments ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY;

    UPDATE public.appointments
    SET id = DEFAULT
    WHERE id IS NULL;

    ALTER TABLE public.appointments ALTER COLUMN id SET NOT NULL;
    ALTER TABLE public.appointments ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);

    CREATE UNIQUE INDEX IF NOT EXISTS idx_appointments_legacy_uuid_id
      ON public.appointments (legacy_uuid_id);
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.next_appointment_id()
RETURNS integer
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT nextval(pg_get_serial_sequence('appointments', 'id'))::integer;
$$;

REVOKE ALL ON FUNCTION public.next_appointment_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.next_appointment_id() TO anon, authenticated;
